### PR TITLE
Add libraries in requirements.txt

### PR DESCRIPTION
**Pull request by tygoee**
You should add libraries [in a `requirements.txt` file](https://docs.python.org/3/tutorial/venv.html) instead of a batch file (I kept the batch file because it'll be easier for other people to install), you can now install it with a single command: `pip install -r requirements.txt`.

### CODE REVIEW

**Comment by RandomGgames** [comment]
Hey thanks for the feedback. I’d take a look at the Dev branch if you want to suggest any changes, as that will contain any changes/improvements I make before releasing. I’ve made a change there a while ago where libraries are automatically installed, definitely check it out.

**Comment by tygoee** [comment]
I see what you did in the dev branch, but I'd take another approach, because when I run it on my linux machine:

```
sh: 1: python: not found
```

and then it throws an ModuleNotFoundError:

```
Traceback (most recent call last):
  File "/home/tygoe/Documents/RMMUD/RMMUD.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

In linux it is `python3` (or `python3.11`) file.py, but when I change that:

```diff
  if importlib.util.find_spec("requests") is None:
-     os.system("python -m pip install requests")
+     os.system("python3 -m pip install requests")
  import requests
  if importlib.util.find_spec("yaml") is None:
-     os.system("python -m pip install pyyaml")
+     os.system("python3 -m pip install pyyaml")
  import yaml
```

You'd still get this error:

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
```

Linux machines don't like packages being installed globally, that's why [virtual environments](https://docs.python.org/3/tutorial/venv.html) are so important. I think there's a way to download libraries the proper way, but I'll look into it tomorrow

**Comment by tygoee** [comment]
I made it on my [code snippets repo](https://github.com/tygoee/code/blob/main/python/autolibs/autolibs-untyped.py), if you like it I can create a pull request to your dev branch?

**Comment by RandomGgames** [comment]
For some reason I didn’t think about other operating systems. I think the simplest option will be make it a manual install, only because I don’t want to add a large function for automatically importing libraries at the beginning. Just a little ocd preference thing. I can update the dev readme and script. Ty though, still appreciate the insight and help.

**Comment by RandomGgames** [comment]
Implemented into dev brance, eventually to be pushed to main and released.

**Pull request closed without merging**
